# Generated by Django 5.0.7 on 2024-07-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                choices=[("1", "Ежедневная"), ("2", "Еженедельная")],
                default=1,
                verbose_name="Период",
            ),
        ),
    ]
