# Generated by Django 5.0.7 on 2024-07-10 03:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_action",
            field=models.DurationField(
                blank="True",
                default=datetime.timedelta(seconds=120),
                null="True",
                verbose_name="Время на выполнение",
            ),
        ),
    ]
