# Generated by Django 5.0.7 on 2024-07-10 17:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_time_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_action",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                verbose_name="Время на выполнение",
            ),
        ),
    ]
